# Generated by Django 2.0.2 on 2018-03-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_tester', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slackuser',
            old_name='name',
            new_name='real_name',
        ),
        migrations.AddField(
            model_name='slackuser',
            name='avatar_url',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackuser',
            name='user_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
