# Generated by Django 2.0.2 on 2018-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_tester', '0002_auto_20180306_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='avatar_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
