# Generated by Django 2.0.2 on 2018-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_tester', '0003_auto_20180306_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackuser',
            options={'ordering': ['is_tester', '-user_name']},
        ),
        migrations.AddField(
            model_name='slackuser',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
    ]
