# Generated by Django 2.0.2 on 2018-03-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('random_tester', '0004_auto_20180306_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUserStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterModelOptions(
            name='slackuser',
            options={'ordering': ['-is_tester', '-user_name']},
        ),
        migrations.AddField(
            model_name='slackuserstack',
            name='slack_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_tester.SlackUser'),
        ),
    ]
